@baseUrl = http://localhost:3000

# @name get_user
GET {{baseUrl}}/users
Content-Type: application/json

###

# @name create_user
POST {{baseUrl}}/users
Content-Type: application/json

{
    "name": "Jeferson Franco",
    "birthDate": "2025-03-25T16:49:53.498Z",
    "gender": "man",
}